### ISSUE TITLE
problems with EliteAPI.dll

### ISSUE THREAD

**Issue by Veedellmuffin** [EasyFarm/EasyFarm#309]
I am at my wits end and I just can't solve this.
I've been using the program for a few days no problems.
Windows 10 did some update, screwed the whole computer up.
Had to do reinstall of pretty much everything.
Reinstalled FFXI
Start up EasyFarm
As soon as I check set character
This error shows up:
An exception has occured
Unable to load DLL 'EliteAPI.dll': Access is denied.
(Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
Then Norton kicks in and deletes the EliteAPI.dll file.
So I fix it up, tell Norton to leave the file and program alone
same thing happens
I went to EliteMMO Network got me the system checker.
I was missing three things,
Got what I was missing everything checks out green
Start things up, same thing happens again.
I'm running this program as an administrator

I'm lost and confused been fighting with this all day
any other help would be appreciated

**Comment by zaxtiss** [comment]
get a new keygen file and update your profile.

**Comment by zaxtiss** [comment]
least thats what i had to do for clipper. not sure about this though.

**Comment by genelhu** [comment]
I had the same error... after I mark the file as an exception to antivirus, or easyfarm crash or windower crash.
I am on windows 10, all green on EliteMMO checker, and i dunno what "get a new keygen file and update your profile" means.

**Comment by fabianoffxi** [comment]
same for me sadly . eliteapi error

**Comment by fabianoffxi** [comment]
fixed it with installing all c++ packs 
https://www.youtube.com/watch?v=nFLnzLY3NSI&t=37s

**Comment by fabianoffxi** [comment]
fixed it with all c++ versions 
uploaded them here https://dailyuploads.net/k0pf5twqkugw?_e_pi_=7%2CPAGE_ID10%2C4901043985

**Comment by redpoetnight** [comment]
I did the update for all C++ versions and I am still having issues with the same error

**Comment by Mykezero** [comment]
@Veedellmuffin  Sorry for the late response. "Access is denied" means that another program is using that dll file. Are you sure Norton is really leaving that file alone?

**Comment by Veedellmuffin** [comment]
Sorry I should have closed this after I fixed it.
I managed to fix the situation with Norton

**Comment by Mykezero** [comment]
Awesome, glad it's working! ^^
